# Generated by Django 4.2 on 2023-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
