# Generated by Django 4.2 on 2023-05-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
