# Generated by Django 4.2.1 on 2023-06-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_remove_bus_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='destination',
            new_name='city1',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='start',
            new_name='city2',
        ),
    ]
